In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob

In [2]:

## Template to get all files in folder with its names then save them as dataframes 

# 1. Look inside your folder and grab every file path that ends with .csv
# (Change 'my_folder/' to the actual path where your files sit)
file_pattern = "E:\\power BI projects\\Maven Market\\data\\*.csv"
all_file_paths = glob.glob(file_pattern)

# 2. Run a loop to read every single CSV into a temporary list of DataFrames
df_list = [pd.read_csv(filename) for filename in all_file_paths]

for index, path in enumerate(all_file_paths):
    # 3. string splitting 
    file_name = path.split('\\')[-1]
    
    # 4. Pass the pre-calculated variable name into the f-string safely
    print(f"Index {index} is file: {file_name}")

Index 0 is file: MavenMarket_Calendar.csv
Index 1 is file: MavenMarket_Customers.csv
Index 2 is file: MavenMarket_Products.csv
Index 3 is file: MavenMarket_Regions.csv
Index 4 is file: MavenMarket_Returns_1997-1998.csv
Index 5 is file: MavenMarket_Stores.csv
Index 6 is file: MavenMarket_Transactions_1997.csv
Index 7 is file: MavenMarket_Transactions_1998.csv

In [3]:
df_calender=df_list[0]
df_customers=df_list[1]
df_products=df_list[2]
df_regions=df_list[3]
df_returns=df_list[4]
df_stores=df_list[5]
df_transactions97=df_list[6]
df_transactions98=df_list[7]

In [4]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  int64
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     10281 non-null  int64
 8   customer_country         10281 non-null  object
 9   birthdate                10281 non-null  object
 10  marital_status           10281 non-null  object
 11  yearly_income            10281 non-null  object
 12  gender                   10281 non-null  object
 13  total_children           10281 non-null  int64
 14  num_children_at_home     10281 non-null  int64
 15  education                10281 non-null  object
 16  acct_open_date           10281 non-null  object
 17  member_card              10281 non-null  object
 18  occupation               10281 non-null  object
 19  homeowner                10281 non-null  object
dtypes: int64(5), object(15)
memory usage: 1.6+ MB

In [5]:
df_customers['yearly_income']

0          $30K - $50K
1          $70K - $90K
2          $50K - $70K
3          $10K - $30K
4          $30K - $50K
             ...
10276     $90K - $110K
10277      $30K - $50K
10278    $130K - $150K
10279          $150K +
10280      $50K - $70K
Name: yearly_income, Length: 10281, dtype: object

In [6]:
df_customers.head()

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,marital_status,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,M,$30K - $50K,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,S,$70K - $90K,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,M,$50K - $70K,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,M,$10K - $30K,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,S,$30K - $50K,F,3,0,Partial College,8/21/1992,Silver,Manual,N

In [7]:
df_customers['yearly_income_min']=df_customers['yearly_income'].str.split('-').str[0]

In [8]:
df_customers

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,...,yearly_income,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner,yearly_income_min
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,...,$30K - $50K,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y,$30K
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,...,$70K - $90K,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N,$70K
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,...,$50K - $70K,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y,$50K
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,...,$10K - $30K,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N,$10K
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,...,$30K - $50K,F,3,0,Partial College,8/21/1992,Silver,Manual,N,$30K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10276,10277,87439274191,Fran,Ross,5603 Blackridge Drive,Lake Oswego,OR,52724,USA,2/9/1974,...,$90K - $110K,M,4,3,Partial High School,3/14/1991,Bronze,Management,N,$90K
10277,10278,87448420500,Myreda,Calahoo,263 La Orinda Pl.,N. Vancouver,BC,71758,Canada,12/8/1926,...,$30K - $50K,F,0,0,Partial College,3/20/1992,Bronze,Professional,N,$30K
10278,10279,87453135848,Mary,Ayers,6885 Auburn,Lincoln Acres,CA,42550,USA,5/18/1913,...,$130K - $150K,M,3,0,Partial High School,11/22/1991,Bronze,Management,Y,$130K
10279,10280,87458639740,Ernest,Aiello,5077 Bannock Ct.,Puyallup,WA,27746,USA,9/6/1968,...,$150K +,F,5,2,High School Degree,5/26/1991,Golden,Professional,Y,$150K +
10280,10281,87460163235,Samuel,Cartney,4609 Parkway Drive,Vancouver,BC,63699,Canada,7/6/1914,...,$50K - $70K,F,5,0,Bachelors Degree,7/22/1993,Bronze,Management,N,$50K

In [9]:
df_customers['yearly_income_max']=df_customers['yearly_income'].str.split('-').str[1]

In [10]:
df_customers

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,...,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner,yearly_income_min,yearly_income_max
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,...,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y,$30K,$50K
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,...,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N,$70K,$90K
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,...,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y,$50K,$70K
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,...,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N,$10K,$30K
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,...,F,3,0,Partial College,8/21/1992,Silver,Manual,N,$30K,$50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10276,10277,87439274191,Fran,Ross,5603 Blackridge Drive,Lake Oswego,OR,52724,USA,2/9/1974,...,M,4,3,Partial High School,3/14/1991,Bronze,Management,N,$90K,$110K
10277,10278,87448420500,Myreda,Calahoo,263 La Orinda Pl.,N. Vancouver,BC,71758,Canada,12/8/1926,...,F,0,0,Partial College,3/20/1992,Bronze,Professional,N,$30K,$50K
10278,10279,87453135848,Mary,Ayers,6885 Auburn,Lincoln Acres,CA,42550,USA,5/18/1913,...,M,3,0,Partial High School,11/22/1991,Bronze,Management,Y,$130K,$150K
10279,10280,87458639740,Ernest,Aiello,5077 Bannock Ct.,Puyallup,WA,27746,USA,9/6/1968,...,F,5,2,High School Degree,5/26/1991,Golden,Professional,Y,$150K +,NaN
10280,10281,87460163235,Samuel,Cartney,4609 Parkway Drive,Vancouver,BC,63699,Canada,7/6/1914,...,F,5,0,Bachelors Degree,7/22/1993,Bronze,Management,N,$50K,$70K

In [11]:
df_customers=df_customers.drop('yearly_income',axis=1)

In [12]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  int64
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     10281 non-null  int64
 8   customer_country         10281 non-null  object
 9   birthdate                10281 non-null  object
 10  marital_status           10281 non-null  object
 11  gender                   10281 non-null  object
 12  total_children           10281 non-null  int64
 13  num_children_at_home     10281 non-null  int64
 14  education                10281 non-null  object
 15  acct_open_date           10281 non-null  object
 16  member_card              10281 non-null  object
 17  occupation               10281 non-null  object
 18  homeowner                10281 non-null  object
 19  yearly_income_min        10281 non-null  object
 20  yearly_income_max        10058 non-null  object
dtypes: int64(5), object(16)
memory usage: 1.6+ MB

In [13]:
df_customers.isnull().sum()

customer_id                  0
customer_acct_num            0
first_name                   0
last_name                    0
customer_address             0
customer_city                0
customer_state_province      0
customer_postal_code         0
customer_country             0
birthdate                    0
marital_status               0
gender                       0
total_children               0
num_children_at_home         0
education                    0
acct_open_date               0
member_card                  0
occupation                   0
homeowner                    0
yearly_income_min            0
yearly_income_max          223
dtype: int64

In [14]:
df_customers['yearly_income_max'].value_counts()

 $50K     3327
 $30K     2222
 $70K     1845
 $90K     1207
 $150K     506
 $130K     493
 $110K     458
Name: yearly_income_max, dtype: int64

In [15]:
df_customers.duplicated().sum()

0

In [16]:
df_customers['yearly_income_max']=df_customers['yearly_income_max'].replace({'\$':'', 'K':''}, regex=True).str.strip()

In [17]:
df_customers['yearly_income_min']=df_customers['yearly_income_min'].replace({'K':'','\$':'','\+':''},regex=True).str.strip()

In [18]:
df_customers

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,...,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner,yearly_income_min,yearly_income_max
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,...,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y,30,50
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,...,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N,70,90
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,...,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y,50,70
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,...,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N,10,30
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,...,F,3,0,Partial College,8/21/1992,Silver,Manual,N,30,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10276,10277,87439274191,Fran,Ross,5603 Blackridge Drive,Lake Oswego,OR,52724,USA,2/9/1974,...,M,4,3,Partial High School,3/14/1991,Bronze,Management,N,90,110
10277,10278,87448420500,Myreda,Calahoo,263 La Orinda Pl.,N. Vancouver,BC,71758,Canada,12/8/1926,...,F,0,0,Partial College,3/20/1992,Bronze,Professional,N,30,50
10278,10279,87453135848,Mary,Ayers,6885 Auburn,Lincoln Acres,CA,42550,USA,5/18/1913,...,M,3,0,Partial High School,11/22/1991,Bronze,Management,Y,130,150
10279,10280,87458639740,Ernest,Aiello,5077 Bannock Ct.,Puyallup,WA,27746,USA,9/6/1968,...,F,5,2,High School Degree,5/26/1991,Golden,Professional,Y,150,NaN
10280,10281,87460163235,Samuel,Cartney,4609 Parkway Drive,Vancouver,BC,63699,Canada,7/6/1914,...,F,5,0,Bachelors Degree,7/22/1993,Bronze,Management,N,50,70

In [19]:
df_customers['yearly_income_min'].value_counts()

30     3327
10     2222
50     1845
70     1207
130     506
110     493
90      458
150     223
Name: yearly_income_min, dtype: int64

In [20]:
df_customers[df_customers['yearly_income_max'].isna()]

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,...,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner,yearly_income_min,yearly_income_max
104,105,88539907932,Sylvester,Valdez,4350 Mota Dr.,National City,CA,35950,USA,5/12/1933,...,M,3,3,Bachelors Degree,2/8/1992,Golden,Management,Y,150,NaN
113,114,88631725311,Marty,Carmona,9263 Mt. McKinley Ct.,Sooke,BC,22047,Canada,4/16/1943,...,F,3,0,High School Degree,3/9/1993,Silver,Professional,Y,150,NaN
135,136,88825504183,Sharon,Haddix,9297 Kenston Dr.,Lynnwood,WA,60392,USA,5/22/1956,...,M,3,3,Bachelors Degree,9/12/1991,Golden,Professional,Y,150,NaN
151,152,89144885540,John,Racette,3454 D Bel Air Drive,Ballard,WA,54647,USA,3/4/1953,...,F,2,0,High School Degree,5/7/1990,Silver,Professional,Y,150,NaN
294,295,90932449102,Donahue,Steen,8144 Ryan Court,Richmond,CA,54272,USA,5/17/1951,...,M,3,0,Partial College,11/16/1992,Silver,Professional,Y,150,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10117,10118,85720348358,Tommy,Tullos,244 La Cadena,Corvallis,OR,56541,USA,10/9/1944,...,F,1,0,Partial High School,1/15/1994,Silver,Professional,Y,150,NaN
10161,10162,86149861216,Bobbie,Williams,8672 Price Lane,San Gabriel,CA,66485,USA,9/25/1961,...,M,1,0,High School Degree,9/24/1994,Golden,Professional,N,150,NaN
10186,10187,86389720439,Michael,Cobb,9774 Maywood Lane,Bellingham,WA,76649,USA,4/19/1974,...,F,3,3,Partial High School,11/26/1992,Golden,Professional,N,150,NaN
10213,10214,86742570400,Jean,Holmes,5507 Worth Ct.,Pomona,CA,46129,USA,11/14/1920,...,F,3,2,Partial High School,10/22/1990,Golden,Management,Y,150,NaN
10279,10280,87458639740,Ernest,Aiello,5077 Bannock Ct.,Puyallup,WA,27746,USA,9/6/1968,...,F,5,2,High School Degree,5/26/1991,Golden,Professional,Y,150,NaN

In [21]:
df_customers['yearly_income_min']=pd.to_numeric(df_customers['yearly_income_min'],errors='coerce') 
df_customers['yearly_income_max']=pd.to_numeric(df_customers['yearly_income_max'],errors='coerce')

In [22]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10281 entries, 0 to 10280
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10281 non-null  int64
 1   customer_acct_num        10281 non-null  int64
 2   first_name               10281 non-null  object
 3   last_name                10281 non-null  object
 4   customer_address         10281 non-null  object
 5   customer_city            10281 non-null  object
 6   customer_state_province  10281 non-null  object
 7   customer_postal_code     10281 non-null  int64
 8   customer_country         10281 non-null  object
 9   birthdate                10281 non-null  object
 10  marital_status           10281 non-null  object
 11  gender                   10281 non-null  object
 12  total_children           10281 non-null  int64
 13  num_children_at_home     10281 non-null  int64
 14  education                10281 non-null  object
 15  acct_open_date           10281 non-null  object
 16  member_card              10281 non-null  object
 17  occupation               10281 non-null  object
 18  homeowner                10281 non-null  object
 19  yearly_income_min        10281 non-null  int64
 20  yearly_income_max        10058 non-null  float64
dtypes: float64(1), int64(6), object(14)
memory usage: 1.6+ MB

In [23]:
df_customers['yearly_income_min']=df_customers['yearly_income_min']*1000 
df_customers['yearly_income_max']=df_customers['yearly_income_max']*1000

In [24]:
df_customers

,customer_id,customer_acct_num,first_name,last_name,customer_address,customer_city,customer_state_province,customer_postal_code,customer_country,birthdate,...,gender,total_children,num_children_at_home,education,acct_open_date,member_card,occupation,homeowner,yearly_income_min,yearly_income_max
0,1,87462024688,Sheri,Nowmer,2433 Bailey Road,Tlaxiaco,Oaxaca,15057,Mexico,8/26/1961,...,F,4,2,Partial High School,9/10/1991,Bronze,Skilled Manual,Y,30000,50000.0
1,2,87470586299,Derrick,Whelply,2219 Dewing Avenue,Sooke,BC,17172,Canada,7/3/1915,...,M,1,0,Partial High School,3/11/1993,Bronze,Professional,N,70000,90000.0
2,3,87475757600,Jeanne,Derry,7640 First Ave.,Issaquah,WA,73980,USA,6/21/1910,...,F,1,1,Bachelors Degree,6/11/1991,Bronze,Professional,Y,50000,70000.0
3,4,87500482201,Michael,Spence,337 Tosca Way,Burnaby,BC,74674,Canada,6/20/1969,...,M,4,4,Partial High School,5/21/1994,Normal,Skilled Manual,N,10000,30000.0
4,5,87514054179,Maya,Gutierrez,8668 Via Neruda,Novato,CA,57355,USA,5/10/1951,...,F,3,0,Partial College,8/21/1992,Silver,Manual,N,30000,50000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10276,10277,87439274191,Fran,Ross,5603 Blackridge Drive,Lake Oswego,OR,52724,USA,2/9/1974,...,M,4,3,Partial High School,3/14/1991,Bronze,Management,N,90000,110000.0
10277,10278,87448420500,Myreda,Calahoo,263 La Orinda Pl.,N. Vancouver,BC,71758,Canada,12/8/1926,...,F,0,0,Partial College,3/20/1992,Bronze,Professional,N,30000,50000.0
10278,10279,87453135848,Mary,Ayers,6885 Auburn,Lincoln Acres,CA,42550,USA,5/18/1913,...,M,3,0,Partial High School,11/22/1991,Bronze,Management,Y,130000,150000.0
10279,10280,87458639740,Ernest,Aiello,5077 Bannock Ct.,Puyallup,WA,27746,USA,9/6/1968,...,F,5,2,High School Degree,5/26/1991,Golden,Professional,Y,150000,NaN
10280,10281,87460163235,Samuel,Cartney,4609 Parkway Drive,Vancouver,BC,63699,Canada,7/6/1914,...,F,5,0,Bachelors Degree,7/22/1993,Bronze,Management,N,50000,70000.0

In [25]:
df_customers['yearly_income_max'].fillna(0,inplace=True)

In [26]:
df_customers.isna().sum()

customer_id                0
customer_acct_num          0
first_name                 0
last_name                  0
customer_address           0
customer_city              0
customer_state_province    0
customer_postal_code       0
customer_country           0
birthdate                  0
marital_status             0
gender                     0
total_children             0
num_children_at_home       0
education                  0
acct_open_date             0
member_card                0
occupation                 0
homeowner                  0
yearly_income_min          0
yearly_income_max          0
dtype: int64

In [27]:
df_products

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,NaN,NaN
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,NaN,1.0
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,1.0,1.0
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,NaN
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,NaN
...,...,...,...,...,...,...,...,...,...
1555,1556,CDR,CDR Creamy Peanut Butter,29538288712,2.65,1.14,6.94,1.0,1.0
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,1.0,NaN
1557,1558,CDR,CDR Extra Chunky Peanut Butter,84930775761,2.16,0.82,11.50,NaN,1.0
1558,1559,CDR,CDR Apple Preserves,75317577719,1.62,0.62,21.00,NaN,NaN
1559,1560,CDR,CDR Grape Jelly,54896665215,1.60,0.74,12.50,NaN,1.0

In [28]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            1560 non-null   int64
 1   product_brand         1560 non-null   object
 2   product_name          1560 non-null   object
 3   product_sku           1560 non-null   int64
 4   product_retail_price  1560 non-null   float64
 5   product_cost          1560 non-null   float64
 6   product_weight        1560 non-null   float64
 7   recyclable            873 non-null    float64
 8   low_fat               552 non-null    float64
dtypes: float64(5), int64(2), object(2)
memory usage: 109.8+ KB

In [29]:
df_products.isna().sum()

product_id                 0
product_brand              0
product_name               0
product_sku                0
product_retail_price       0
product_cost               0
product_weight             0
recyclable               687
low_fat                 1008
dtype: int64

In [30]:
df_products['recyclable'].value_counts()

1.0    873
Name: recyclable, dtype: int64

In [31]:
df_products['recyclable'].fillna(0,inplace=True)

In [32]:
df_products.isna().sum()

product_id                 0
product_brand              0
product_name               0
product_sku                0
product_retail_price       0
product_cost               0
product_weight             0
recyclable                 0
low_fat                 1008
dtype: int64

In [33]:
df_products['low_fat'].value_counts()

1.0    552
Name: low_fat, dtype: int64

In [34]:
df_products['low_fat'].fillna(0,inplace=True)

In [35]:
df_products.isna().sum()

product_id              0
product_brand           0
product_name            0
product_sku             0
product_retail_price    0
product_cost            0
product_weight          0
recyclable              0
low_fat                 0
dtype: int64

In [36]:
df_products

,product_id,product_brand,product_name,product_sku,product_retail_price,product_cost,product_weight,recyclable,low_fat
0,1,Washington,Washington Berry Juice,90748583674,2.85,0.94,8.39,0.0,0.0
1,2,Washington,Washington Mango Drink,96516502499,0.74,0.26,7.42,0.0,1.0
2,3,Washington,Washington Strawberry Drink,58427771925,0.83,0.40,13.10,1.0,1.0
3,4,Washington,Washington Cream Soda,64412155747,3.64,1.64,10.60,1.0,0.0
4,5,Washington,Washington Diet Soda,85561191439,2.19,0.77,6.66,1.0,0.0
...,...,...,...,...,...,...,...,...,...
1555,1556,CDR,CDR Creamy Peanut Butter,29538288712,2.65,1.14,6.94,1.0,1.0
1556,1557,CDR,CDR Strawberry Preserves,50687324404,1.20,0.48,15.40,1.0,0.0
1557,1558,CDR,CDR Extra Chunky Peanut Butter,84930775761,2.16,0.82,11.50,0.0,1.0
1558,1559,CDR,CDR Apple Preserves,75317577719,1.62,0.62,21.00,0.0,0.0
1559,1560,CDR,CDR Grape Jelly,54896665215,1.60,0.74,12.50,0.0,1.0

In [37]:
df_regions

     region_id sales_district    sales_region
0            1  San Francisco    Central West
1            2    Mexico City  Mexico Central
2            3    Los Angeles      South West
3            4    Guadalajara     Mexico West
4            5      Vancouver     Canada West
..         ...            ...             ...
104        105       Victoria     Canada West
105        106    Mexico City  Mexico Central
106        107    Mexico City  Mexico Central
107        108    Mexico City  Mexico Central
108        109    Mexico City  Mexico Central

[109 rows x 3 columns]

In [38]:
df_regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region_id       109 non-null    int64
 1   sales_district  109 non-null    object
 2   sales_region    109 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.7+ KB

In [39]:
df_regions.isna().sum()

region_id         0
sales_district    0
sales_region      0
dtype: int64

In [40]:
df_regions.duplicated().sum()

0

In [41]:
df_returns

     return_date  product_id  store_id  quantity
0       1/1/1997         250         6         1
1       1/1/1997         628         6         1
2       1/1/1997         869         6         1
3       1/2/1997         469        11         1
4       1/2/1997         532        23         2
...          ...         ...       ...       ...
7082  12/30/1998        1037        11         2
7083  12/30/1998        1048        10         1
7084  12/30/1998        1065        10         1
7085  12/30/1998        1154        11         1
7086  12/30/1998        1291        11         1

[7087 rows x 4 columns]

In [42]:
df_returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7087 entries, 0 to 7086
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   return_date  7087 non-null   object
 1   product_id   7087 non-null   int64
 2   store_id     7087 non-null   int64
 3   quantity     7087 non-null   int64
dtypes: int64(3), object(1)
memory usage: 221.6+ KB

In [43]:
df_returns.isna().sum()

return_date    0
product_id     0
store_id       0
quantity       0
dtype: int64

In [44]:
df_returns.duplicated().sum()

5

In [45]:
df_returns.duplicated().value_counts()

False    7082
True        5
dtype: int64

In [46]:
df_returns[df_returns.duplicated(keep=False)].sort_values(by='product_id')

     return_date  product_id  store_id  quantity
3226   3/12/1998         264        11         1
3227   3/12/1998         264        11         1
1116    7/6/1997         484        13         1
1117    7/6/1997         484        13         1
4935   7/27/1998         661         4         1
4936   7/27/1998         661         4         1
5196   8/18/1998        1153        13         1
5197   8/18/1998        1153        13         1
6558  11/28/1998        1212        19         1
6559  11/28/1998        1212        19         1

In [47]:
df_returns.drop_duplicates(inplace=True)

In [48]:
df_returns[df_returns.duplicated(keep=False)]

Empty DataFrame
Columns: [return_date, product_id, store_id, quantity]
Index: []

In [49]:
df_returns.duplicated().sum()

0

In [50]:
df_stores

,store_id,region_id,store_type,store_name,store_street_address,store_city,store_state,store_country,store_phone,first_opened_date,last_remodel_date,total_sqft,grocery_sqft
0,1,28,Supermarket,Store 1,2853 Bailey Rd,Acapulco,Guerrero,Mexico,262-555-5124,1/9/1982,12/5/1990,23593,17475
1,2,78,Small Grocery,Store 2,5203 Catanzaro Way,Bellingham,WA,USA,605-555-8203,4/2/1970,6/4/1973,28206,22271
2,3,76,Supermarket,Store 3,1501 Ramsey Circle,Bremerton,WA,USA,509-555-1596,6/14/1959,11/19/1967,39696,24390
3,4,27,Gourmet Supermarket,Store 4,433 St George Dr,Camacho,Zacatecas,Mexico,304-555-1474,9/27/1994,12/1/1995,23759,16844
4,5,4,Small Grocery,Store 5,1250 Coggins Drive,Guadalajara,Jalisco,Mexico,801-555-4324,9/18/1978,6/29/1991,24597,15012
5,6,47,Gourmet Supermarket,Store 6,5495 Mitchell Canyon Road,Beverly Hills,CA,USA,958-555-5002,1/3/1981,3/13/1991,23688,15337
6,7,3,Supermarket,Store 7,1077 Wharf Drive,Los Angeles,CA,USA,477-555-7967,5/21/1971,10/20/1981,23598,14210
7,8,26,Deluxe Supermarket,Store 8,3173 Buena Vista Ave,Merida,Yucatan,Mexico,797-555-3417,9/23/1958,11/18/1967,30797,20141
8,9,2,Mid-Size Grocery,Store 9,1872 El Pintado Road,Mexico City,DF,Mexico,439-555-3524,3/18/1955,6/7/1959,36509,22450
9,10,24,Supermarket,Store 10,7894 Rotherham Dr,Orizaba,Veracruz,Mexico,212-555-4774,4/13/1979,1/30/1982,34791,26354
10,11,22,Supermarket,Store 11,5371 Holland Circle,Portland,OR,USA,685-555-8995,9/17/1976,5/15/1982,20319,16232
11,12,25,Deluxe Supermarket,Store 12,1120 Westchester Pl,Hidalgo,Zacatecas,Mexico,151-555-1702,3/25/1968,12/18/1993,30584,21938
12,13,23,Deluxe Supermarket,Store 13,5179 Valley Ave,Salem,OR,USA,977-555-2724,4/13/1957,11/10/1997,27694,18670
13,14,1,Small Grocery,Store 14,4365 Indigo Ct,San Francisco,CA,USA,135-555-4888,11/24/1957,1/7/1958,22478,15321
14,15,18,Supermarket,Store 15,5006 Highland Drive,Seattle,WA,USA,893-555-1024,7/24/1969,10/19/1973,21215,13305
15,16,87,Supermarket,Store 16,5922 La Salle Ct,Spokane,WA,USA,643-555-3645,8/23/1974,7/13/1977,30268,22063
16,17,84,Deluxe Supermarket,Store 17,490 Risdon Road,Tacoma,WA,USA,855-555-5581,5/30/1970,6/23/1976,33858,22123
17,18,25,Mid-Size Grocery,Store 18,6764 Glen Road,Hidalgo,Zacatecas,Mexico,528-555-8317,6/28/1969,8/30/1975,38382,30351
18,19,5,Deluxe Supermarket,Store 19,6644 Sudance Drive,Vancouver,BC,Canada,862-555-7395,3/27/1977,10/25/1990,23112,16418
19,20,6,Mid-Size Grocery,Store 20,3706 Marvelle Ln,Victoria,BC,Canada,897-555-1931,2/6/1980,4/9/1987,34452,27463
20,21,106,Deluxe Supermarket,Store 21,4093 Steven Circle,San Andres,DF,Mexico,493-555-4781,2/7/1986,4/16/1990,32717,25453
21,22,88,Small Grocery,Store 22,9606 Julpum Loop,Walla Walla,WA,USA,881-555-5117,1/24/1951,10/17/1969,35918,24837
22,23,89,Mid-Size Grocery,Store 23,3920 Noah Court,Yakima,WA,USA,170-555-8424,7/16/1977,7/24/1987,29182,19283
23,24,7,Supermarket,Store 24,2342 Waltham St.,San Diego,CA,USA,111-555-0303,5/22/1979,4/20/1986,27372,18293

In [51]:
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     object
 3   store_name            24 non-null     object
 4   store_street_address  24 non-null     object
 5   store_city            24 non-null     object
 6   store_state           24 non-null     object
 7   store_country         24 non-null     object
 8   store_phone           24 non-null     object
 9   first_opened_date     24 non-null     object
 10  last_remodel_date     24 non-null     object
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     int64
dtypes: int64(4), object(9)
memory usage: 2.6+ KB

In [52]:
df_stores.duplicated().sum()

0

In [53]:
df_stores['store_phone']=df_stores['store_phone'].str.split('-').str.join('')

In [54]:
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     object
 3   store_name            24 non-null     object
 4   store_street_address  24 non-null     object
 5   store_city            24 non-null     object
 6   store_state           24 non-null     object
 7   store_country         24 non-null     object
 8   store_phone           24 non-null     object
 9   first_opened_date     24 non-null     object
 10  last_remodel_date     24 non-null     object
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     int64
dtypes: int64(4), object(9)
memory usage: 2.6+ KB

In [55]:
df_stores['store_phone']=pd.to_numeric(df_stores['store_phone'],errors='coerce')

In [56]:
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store_id              24 non-null     int64
 1   region_id             24 non-null     int64
 2   store_type            24 non-null     object
 3   store_name            24 non-null     object
 4   store_street_address  24 non-null     object
 5   store_city            24 non-null     object
 6   store_state           24 non-null     object
 7   store_country         24 non-null     object
 8   store_phone           24 non-null     int64
 9   first_opened_date     24 non-null     object
 10  last_remodel_date     24 non-null     object
 11  total_sqft            24 non-null     int64
 12  grocery_sqft          24 non-null     int64
dtypes: int64(5), object(8)
memory usage: 2.6+ KB

In [57]:
df_transactions97.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86837 entries, 0 to 86836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_date  86837 non-null  object
 1   stock_date        86837 non-null  object
 2   product_id        86837 non-null  int64
 3   customer_id       86837 non-null  int64
 4   store_id          86837 non-null  int64
 5   quantity          86837 non-null  int64
dtypes: int64(4), object(2)
memory usage: 4.0+ MB

In [58]:
df_transactions97.duplicated().sum()

1

In [59]:
df_transactions97[df_transactions97.duplicated(keep=False)]

      transaction_date stock_date  product_id  customer_id  store_id  quantity
28560         5/2/1997   5/1/1997         290         1690        16         3
28638         5/2/1997   5/1/1997         290         1690        16         3

In [60]:
df_transactions97=df_transactions97.drop_duplicates()

In [61]:
df_transactions97.duplicated().sum()

0

In [62]:
df_transactions97.isna().sum()

transaction_date    0
stock_date          0
product_id          0
customer_id         0
store_id            0
quantity            0
dtype: int64

In [63]:
df_transactions98

,transaction_date,stock_date,product_id,customer_id,store_id,quantity
0,1/1/1998,12/25/1997,4,2439,10,3
1,1/1/1998,12/28/1997,11,4284,10,3
2,1/1/1998,12/28/1997,12,534,10,3
3,1/1/1998,12/29/1997,14,9743,10,2
4,1/1/1998,12/27/1997,16,3608,10,3
...,...,...,...,...,...,...
182878,12/30/1998,12/29/1998,1521,7197,11,3
182879,12/30/1998,12/23/1998,1536,5223,10,2
182880,12/30/1998,12/23/1998,1542,8077,10,4
182881,12/30/1998,12/28/1998,1544,4485,10,2
182882,12/30/1998,12/29/1998,1549,5223,10,3

In [64]:
df_transactions98.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182883 entries, 0 to 182882
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_date  182883 non-null  object
 1   stock_date        182883 non-null  object
 2   product_id        182883 non-null  int64
 3   customer_id       182883 non-null  int64
 4   store_id          182883 non-null  int64
 5   quantity          182883 non-null  int64
dtypes: int64(4), object(2)
memory usage: 8.4+ MB

In [65]:
df_transactions98.isna().sum()

transaction_date    0
stock_date          0
product_id          0
customer_id         0
store_id            0
quantity            0
dtype: int64

In [66]:
df_transactions98.duplicated().sum()

8

In [67]:
df_transactions98=df_transactions98.drop_duplicates()

In [68]:
df_transactions98.duplicated().sum()

0

In [69]:
df_transactions=pd.concat([df_transactions97,df_transactions98],axis=0,ignore_index=True)

In [70]:
df_transactions

,transaction_date,stock_date,product_id,customer_id,store_id,quantity
0,1/1/1997,12/31/1996,869,3449,6,5
1,1/1/1997,12/31/1996,1472,3449,6,3
2,1/1/1997,12/28/1996,76,3449,6,4
3,1/1/1997,12/26/1996,320,3449,6,3
4,1/1/1997,12/25/1996,4,3449,6,4
...,...,...,...,...,...,...
269706,12/30/1998,12/29/1998,1521,7197,11,3
269707,12/30/1998,12/23/1998,1536,5223,10,2
269708,12/30/1998,12/23/1998,1542,8077,10,4
269709,12/30/1998,12/28/1998,1544,4485,10,2
269710,12/30/1998,12/29/1998,1549,5223,10,3

In [71]:
df_transactions.isna().sum()

transaction_date    0
stock_date          0
product_id          0
customer_id         0
store_id            0
quantity            0
dtype: int64

In [72]:
df_transactions.duplicated().sum()

0

In [73]:
df_transactions

,transaction_date,stock_date,product_id,customer_id,store_id,quantity
0,1/1/1997,12/31/1996,869,3449,6,5
1,1/1/1997,12/31/1996,1472,3449,6,3
2,1/1/1997,12/28/1996,76,3449,6,4
3,1/1/1997,12/26/1996,320,3449,6,3
4,1/1/1997,12/25/1996,4,3449,6,4
...,...,...,...,...,...,...
269706,12/30/1998,12/29/1998,1521,7197,11,3
269707,12/30/1998,12/23/1998,1536,5223,10,2
269708,12/30/1998,12/23/1998,1542,8077,10,4
269709,12/30/1998,12/28/1998,1544,4485,10,2
269710,12/30/1998,12/29/1998,1549,5223,10,3

In [74]:
df_customers.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\customers.csv", index=False)
df_calender.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\calender.csv", index=False)
df_products.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\products.csv", index=False)
df_regions.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\regions.csv", index=False)
df_returns.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\returns.csv", index=False)
df_stores.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\stores.csv", index=False)
df_transactions.to_csv("E:\\power BI projects\\Maven Market\\Data for power BI (cleaned)\\transactions.csv", index=False)

In [75]:
df_calender

           date
0      1/1/1997
1      1/2/1997
2      1/3/1997
3      1/4/1997
4      1/5/1997
..          ...
725  12/27/1998
726  12/28/1998
727  12/29/1998
728  12/30/1998
729  12/31/1998

[730 rows x 1 columns]